# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardpreferences',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dashboardpreferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardPreferences',
        ),
    ]
